### ISSUE TITLE
Dungeons healing FCT

### ISSUE THREAD

**Issue by 73mates** [kodewdle/ElvUI_FCT#10]
Hi, when I'm in dungeon, it won't show floating combat text for healing my allies. But damage it showing with no problem.
I have tried this command (/console floatingCombatTextCombatHealing 1) and still nothing.

Do you know what could be the problem?

Thanks!

**Comment by kodewdle** [comment]
nameplates in dungeons are protected by blizzard so addons can't really do anything with them.  
![image](https://user-images.githubusercontent.com/2266754/211122147-4ad31ac5-a61e-4764-b9c5-f523e04e4f03.png)
