### ISSUE TITLE
Floating combat text above nameplates

### ISSUE THREAD

**Issue by johannes-michael** [kodewdle/ElvUI_FCT#11]
The floating combat text for nameplates is visually above the nameplates, which makes it reallly hard to see in M+ for example. In the options I didn't find any settings for the frame strata level. Is this how it's supposed to work? Normal floating combat text is always behind nameplates for visibility reasons.

**Comment by kodewdle** [comment]
https://github.com/kodewdle/ElvUI_FCT/issues/1 it's on the TODO but most of my time is dedicated to ElvUI itself so no ETA 🌼
