### ISSUE TITLE
Sorted Unitframes

### ISSUE THREAD

**Issue by Vanadin1** [kodewdle/ElvUI_FCT#16]
Hello!

I have my unitframes set up using Elvui to sort role order, as seen in the attached image. 

https://i.imgur.com/XQV4qQx.png

When I am healing the tank, it heals party member #3 instead of #2 (the tank)

As you can see in the image below, I have healed the tank for 50.9k. The animation of the floating text however is coming out of the hunter. When I heal the hunter, the animation comes out of the tank's unitframe. 

https://i.imgur.com/h7RdGOL.png

Thanks!

https://i.imgur.com/q4KzlQQ.png

https://i.imgur.com/yJ2hQFQ.png

**Comment by kodewdle** [comment]
check the offsets because the sorting order is not used at all by FCT
FCT runs purely off of the units token (which is set on the unitframe itself)
if that were to be changed, the unitframe would be displaying incorrect name, etc.
