### ISSUE TITLE
Tukui client retired

### ISSUE THREAD

**Issue by djodars89** [kodewdle/ElvUI_FCT#18]
Hi there,

Seeing as Tukui client is no more and the addon isn't available on the website either, would it be possible to make the github WoWUP compatible?

I think it only needs a .zip in order to be recognized by WoWUP's client.
See GitHub note here: https://wowup.io/guide/get-addons/overview

Thank you so much!

Edit: Or add the addon on Curse / WowUpHub

**Comment by kodewdle** [comment]
done 👍
