### ISSUE TITLE
nur ein simple3dportraits

### ISSUE THREAD

**Issue by Vidarius** [kodewdle/ElvUI_FCT#21]
Seit 2010 gab es das AddOn (https://www.wowace.com/projects/simple3dportraits) aber seit nun ca. 1,5 Jahren will es nicht mehr und ich bekomme es auch nicht hin, da ich kein Programmierer bin. Ich biete 10€ Spende an für das wieder nutzbar machen.

Letztes Offizielles Update war von Sep 9, 2012 (WoW Retail 5.0.4) https://www.wowace.com/projects/simple3dportraits/files/624815

Lief also locker weiter 10 Jahre, aber nun eben nicht mehr so richtig.
Da Ihr aber in Eurem ElvUI Paket ebenfalls 3D Portraits nutz, bin ich davon Überzeugt das Ihr die ca. 800 Zeilen Code schnell durch habt und das Problem sicher leicht lösen könnt.

-----
Since 2010 there was the AddOn (https://www.wowace.com/projects/simple3dportraits) but for about 1.5 years now it doesn't want it anymore and I can't get it to work because I'm not a programmer. I offer 10$ donation for making it usable again.

Last official update was from Sep 9, 2012 (WoW Retail 5.0.4) https://www.wowace.com/projects/simple3dportraits/files/624815

So it's been running for another 10 years, but not really anymore.
But since you also use 3D portraits in your ElvUI package, I am convinced that you have quickly gone through the approx. 800 lines of code and can easily solve the problem.

Translated with DeepL.com (free version)

![Simple3DFrames_1](https://github.com/kodewdle/ElvUI_FCT/assets/20396855/ffc66740-a241-4439-8231-2e15ab83fd8e)
![Simple3DFrames_a](https://github.com/kodewdle/ElvUI_FCT/assets/20396855/68c07f21-cde4-469b-aa28-72219c9dcad4)
![Simple3DFrames_b](https://github.com/kodewdle/ElvUI_FCT/assets/20396855/9c376c75-969e-4968-89f3-7042be2064fd)
![Simple3DFramesUnlocked](https://github.com/kodewdle/ElvUI_FCT/assets/20396855/e1c4519e-a0a6-41b1-8fcd-26a1ca8c0301)

**Comment by kodewdle** [comment]
sorry, this isn't related to this repo

**Comment by Vidarius** [comment]
what is repo? i cant translate it... 800 lines code and i think only 5 lines need a update or so... please, i pay for your work

**Comment by Repooc** [comment]
repo = repository, he already declined as he is not interested

**Comment by Vidarius** [comment]
also not with pay for work - why?

**Comment by Repooc** [comment]
It doesnt matter for pay or not... If some one says they are not interested, pay means nothing when someone is not interested in doing what you want
