### ISSUE TITLE
FCT doesnt seem to be showing up

### ISSUE THREAD

**Issue by codedbymatt** [kodewdle/ElvUI_FCT#3]
i have disabled all addons besides ELVUI and FCT and it doesnt seem to want to show up

**Comment by kodewdle** [comment]
make sure you installed it to the correct addon folder

**Comment by codedbymatt** [comment]
I figured it out, I had it enabled elsewhere in another addon

*Sent from Mail for Windows*

**Comment by kodewdle** [comment]
i did add support for other nameplate addons last night, if that's what you mean.  i haven't updated the version yet but i'm testing it!  :)

**Comment by codedbymatt** [comment]
Okay awesome

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
