### ISSUE TITLE
X and Y offsets do not seem to work

### ISSUE THREAD

**Issue by jposavatz** [kodewdle/ElvUI_FCT#4]
Perhaps I'm "doing it wrong", but combat text isn't showing up exactly where I want it (centered within my Unit Frame health bar). I've attempted to adjust the Offsets for Text X, Text Y, Spell X, Spell Y (so far only for "Player") ... but none seem to have any affect.

**Comment by kodewdle** [comment]
https://user-images.githubusercontent.com/2266754/167096714-ec1c058d-8734-4c1b-9091-041f20d212fd.mp4

it seems to work properly.
