### ISSUE TITLE
Compatibility with WoWUP addon manager

### ISSUE THREAD

**Issue by Smexhy** [kodewdle/ElvUI_FCT#5]
![image](https://user-images.githubusercontent.com/4880625/188661274-a776d84f-03d5-481f-9c8a-04704e0c4455.png)

Hey, would it be possible to make this addon compatible to import into wowup through Github?

**Comment by Repooc** [comment]
U should be able to use wowup by searching for it as they support grabbing
addons from the tukui site as I believe he hosts it there. Just browse for
new addon like normal instead of trying to do the GitHub way

**Comment by kodewdle** [comment]
what repooc said, not going to change anything in this repo outside of what is here just get it from tukui or tukui section of your updater.
