### ISSUE TITLE
Translate "NamePlates"

### ISSUE THREAD

**Issue by Hollicsh** [kodewdle/ElvUI_FCT#8]
Hey Simpy !
In ElvUI, this word is written with a capital letter, and all the rest are small. In your code, this word is capitalized and the second word is also capitalized. On the Russian client, this phrase was not translated.

![Screenshot_1](https://user-images.githubusercontent.com/54585769/191843792-423c7680-59dc-4f82-88b2-ebb4ca8adff5.png)

v. 1.22

**Comment by kodewdle** [comment]
thanks, updated it on this side to match ElvUI
