### ISSUE TITLE
Addon is not listed under Classic WotLK category on Tukui

### ISSUE THREAD

**Issue by Smexhy** [kodewdle/ElvUI_FCT#9]
Hello, I noticed that your addon isn't listed under WotLK category on Tukui website, therefore we won't be able to update it through the addon managers - only for retail. Would it be possible to list it as WotLK addon on Tukui as well please? It would help a ton, love your addon.

**Comment by kodewdle** [comment]
I will consider this some more, thanks for suggesting! 🌼
